# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KiClockExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KiClock', :git => 'https://github.com/soledue/kiclock.git', :branch => 'develop'
  # Pods for KiClockExample

end
